# Cyberpunk 1980s Retrofuturistic Color Scheme
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#333333"      # dark gray
blue = "#4080ff"      # bright electric blue
cyan = "#40ffff"      # bright neon cyan
green = "#40ff40"     # bright neon green
magenta = "#ff40ff"   # bright neon magenta
red = "#ff4080"       # bright neon red
white = "#ffffff"     # white
yellow = "#ffff40"    # bright neon yellow

[colors.normal]
black = "#000000"     # black
blue = "#0080ff"      # electric blue
cyan = "#00ffff"      # neon cyan
green = "#00ff00"     # neon green
magenta = "#ff00ff"   # neon magenta
red = "#ff0040"       # neon red
white = "#cccccc"     # light gray
yellow = "#ffff00"    # neon yellow

[colors.primary]
background = "#000000"  # black background
foreground = "#00ffff"  # neon cyan text

[colors.cursor]
# Cyberpunk cyan cursor
text = "#000000"        # black text on cursor
cursor = "#00ffff"      # neon cyan cursor

[cursor]
style = "Block"
# Cursor color is controlled by colors.cursor section below

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
# Alternative retro fonts: "IBM Plex Mono", "Courier New", "Terminus"

[font.bold_italic]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
# Slightly more opaque for better cyberpunk visibility
opacity = 0.95
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[general]
live_config_reload = true

[terminal]
