"$schema" = 'https://starship.rs/config-schema.json'

## CYBERPUNK 1980s RETROFUTURISTIC THEME
## Colors: Neon Cyan (#00FFFF), Neon Magenta (#FF00FF), Neon Green (#00FF00)
## Dark Background (#000000), Accent Red (#FF0040), Accent Yellow (#FFFF00)

format = """
[░▒▓](#00ffff)\
[  ](bg:#00ffff fg:#000000)\
[ ](bg:#00ff00 fg:#00ffff)\
$directory\
[ ](fg:#00ff00 bg:#ff00ff)\
[ ](fg:#ff00ff bg:#00ffff)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#00ffff bg:#ffff00)\
$time\
[ ](fg:#ffff00)\
\n$character"""

[directory]
style = "fg:#000000 bg:#00ff00 bold"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "/home/pekka/Documents/"
"Downloads" = "/home/pekka/Downloads/"
"Music" = "/home/pekka/Oxbacka/Music/"
"Dots" = "/home/pekka/.dotfiles"

[git_branch]
symbol = ""
style = "bg:#ff00ff"
format = '[[ $symbol $branch ](fg:#000000 bg:#ff00ff bold)]($style)'

[git_status]
style = "bg:#ff00ff"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#ff00ff bold)]($style)'

[nodejs]
symbol = ""
style = "bg:#00ffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#00ffff bold)]($style)'

[rust]
symbol = ""
style = "bg:#00ffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#00ffff bold)]($style)'

[golang]
symbol = ""
style = "bg:#00ffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#00ffff bold)]($style)'

[php]
symbol = ""
style = "bg:#00ffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#00ffff bold)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ffff00"
format = '[[  $time ](fg:#000000 bg:#ffff00 bold)]($style)'

[character]
success_symbol = "[>](fg:#00ffff bold)"
error_symbol = "[×](fg:#ff0040 bold)"
vicmd_symbol = "[V](fg:#ff00ff bold)"
